import NavBar from "../components/ui/NavBar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main className="container mx-auto px-4 py-6">{children}</main>
      </body>
    </html>
  );
}
