import NavBar from "../ui/NavBar";

import Footer from "../ui/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ClientLayout({ children }) {
  return (
    <div className="flex flex-col min-h-screen">
      <NavBar />
      <main className="container mx-auto px-4 py-6 flex-1 ">{children}</main>
      <Footer />
    </div>
  );
}
